[tool.black]
line-length = 85

[tool.isort]
profile = "black"
known_first_party = ["keras_tuner", "tests"]
default_section = "THIRDPARTY"
line_length = 85
skip_glob = "keras_tuner/protos/*"
force_single_line = "True"