name: Integration tests using keras.io guides

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip setuptools
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
      - name: Install dependencies
        run: |
          pip install -e ".[tests]" --progress-bar off --upgrade
      - name: Run the guides
        run: |
          bash shell/run_guides.sh
